INSERT INTO USER (EMAIL,PASSWORD,USERNAME) VALUES ('admin@email.com','$2a$12$AMrY80vMcQ7S4xd8XOErqud9oUtcxu2PEMbHJFPBbdmZIJMHefRmO','admin');
INSERT INTO USER (EMAIL,PASSWORD,USERNAME) VALUES ('client@email.com','$2a$12$KufXxvGzmVr8AFCfI3FxbexmQ6goSSmJeyNsxlgt5ym2ltFouadoO','client');

INSERT INTO USER_ROLES (USER_ID,ROLES) VALUES (1,0);
INSERT INTO USER_ROLES (USER_ID,ROLES) VALUES (2,1);

INSERT INTO PRODUCT (NAME,PRICE) VALUES ('PS4',0.004);
INSERT INTO PRODUCT (NAME,PRICE) VALUES ('XBOX ONE',0.0043);
INSERT INTO PRODUCT (NAME,PRICE) VALUES ('PS5',0.008);
INSERT INTO PRODUCT (NAME,PRICE) VALUES ('XBOX S',0.0085);